4.12 Сетка страниц на флексах
htmlacademy-htmlcss/929041-device-32 pull request #5
Opened 2021-11-06 14:06 UTC by sh00rs

Добавляет крупную сетку страниц.

2021-11-07 09:25 UTC, PavelNyukalo requested changes

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +  margin: 0;
Тут так же про `wrapper`

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +  max-width: 1160px;
Аналогично, но в принципе можно не задавать, поскольку ширина указана у `main-container`, и весь внутренний контент подстраивается под эту ширину

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +h3.about.title {
Глобальный тег, запрещено. Можно сделать новый класс, например `about-title` и через него

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +  margin: 0 auto;
Аналогично про `wrapper`

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +}
1. Почему 315fr и 685fr? Вот еще есть [статья про fr](https://medium.com/@stasonmars/что-такое-единица-гибкости-fr-в-css-доступным-и-простым-языком-2a3794c4444)
2. Надо тоже центрировать, ибо может получиться такая ситуация: 
![image](https://user-images.githubusercontent.com/52506235/140637539-ddbb64cc-990a-4650-b333-c6b785266fd6.png)

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +}
По сути, это лишняя обертка, можно стилизовать саму форму

2021-11-07 09:25 UTC, PavelNyukalo commented on styles/styles.css
> +}
Это тоже лишние обертки, у нас есть `products-list`, через него и стилизуем

2021-11-08 19:27 UTC, sh00rs commented on styles/styles.css
> +h3.about.title {
Я поправил. Но h3.about.title не кажется мне глобальным. Я ведь указываю, что должно быть одновременно несколько классов. Что может пойти не так?

2021-11-08 21:33 UTC, sh00rs commented on styles/styles.css
> +}
Как растянуть фон под блоком фильтра до края экрана и одновременно отцентровать содержимое я пока не придумал. Это главная засада в этом задании.

2021-11-09 08:32 UTC, PavelNyukalo commented on styles/styles.css
> +}
Для `page-header` тоже надо задать `padding` (а это уже у нас класс `wrapper`), чтобы он тоже не прилипал к краю
![image](https://user-images.githubusercontent.com/52506235/140888588-90b67971-51bf-43bf-9a82-1acbb09df5f4.png)

2021-11-09 08:32 UTC, PavelNyukalo commented on styles/styles.css
> +  padding: 0 60px;
Тут лучше не 60, а 20 дать, не нашел в критериях текущего потока, но раньше максимальная ширина с учетом `padding` была 1200
![image](https://user-images.githubusercontent.com/52506235/140888976-d20562b7-50da-466e-a8d0-e0d7c5c6ab54.png)

2021-11-09 08:32 UTC, PavelNyukalo commented on styles/styles.css
> +h3.about.title {
Жесткая привязка идет, это надо чтобы был заголовок 3 уровня, + один класс, + второй. А стили могут потребоваться на другом заголовке, но уже другого уровня, проще добавить класс, чем прописывать снова `h4.about.title` и тд

2021-11-09 09:03 UTC, PavelNyukalo commented on styles/styles.css
> +}
Тут можно не гридами, а например флексами сделать, добавить пару оберток. Либо гриды использовать тоже внутри обертки, а обертку растягивать на всю ширину
Вот как можно разбить флексами: (две колонки красные, и уже внутри них другие блоки)
![image](https://user-images.githubusercontent.com/52506235/140894382-81ce2217-8378-4a51-9517-dbc8c214369a.png)

2021-11-09 09:10 UTC, PavelNyukalo requested changes

2021-11-09 09:10 UTC, PavelNyukalo commented on styles/styles.css
> +  padding: 0 60px;
Тут надо не 60, а 20, не нашел в этом потоке критерия, но раньше писали вот:
![image](https://user-images.githubusercontent.com/52506235/140895416-3beddb91-be82-4f01-bdc8-247135f04599.png)

Давай сделаем так же

2021-11-09 18:31 UTC, sh00rs commented on styles/styles.css
> +  padding: 0 60px;
Ну да, 1160 + 120 1200 не получится.

2021-11-09 18:32 UTC, sh00rs commented on styles/styles.css
> +}
.page-header удалил, класс wrapper добавил в список стилей в разметке.

2021-11-11 18:35 UTC, sh00rs commented on styles/styles.css
> +}
Как сделать на флексах, я так и не понял. В дискорде почерпнул мысль, как сделать на гридах.

2021-11-12 17:57 UTC, PavelNyukalo approved these changes

2021-11-12 17:58 UTC, merged